language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
#  - OCAML_VERSION=4.03 PINS="ocsigenserver:https://github.com/ocsigen/ocsigenserver.git deriving:https://github.com/ocsigen/deriving.git" PACKAGE=eliom
#  - OCAML_VERSION=4.04 PINS="ocsigenserver:https://github.com/ocsigen/ocsigenserver.git deriving:https://github.com/ocsigen/deriving.git" PACKAGE=eliom
#  - OCAML_VERSION=4.05 PINS="ocsigenserver:https://github.com/ocsigen/ocsigenserver.git deriving:https://github.com/ocsigen/deriving.git" PACKAGE=eliom
#  - OCAML_VERSION=4.06 PINS="ocsigenserver:https://github.com/ocsigen/ocsigenserver.git deriving:https://github.com/ocsigen/deriving.git" PACKAGE=eliom
  - OCAML_VERSION=4.07 PACKAGE=eliom
os:
  - linux
  - osx

branches:
  except:
  - wikidoc
